# Generated by Django 3.0.7 on 2020-06-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20200604_0859'),
        ('configuracion', '0002_auto_20200603_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grado',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='ValoracionLetra',
        ),
    ]
