# Generated by Django 3.0.7 on 2020-06-04 13:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20200603_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionLetra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('valor_numerico', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='equivalencia',
            name='rango_simbolo_mayor',
            field=models.CharField(choices=[('>', '>'), ('<', '<'), ('>=', '>='), ('<=', '<='), ('=', '=')], max_length=10),
        ),
        migrations.AlterField(
            model_name='equivalencia',
            name='rango_simbolo_menor',
            field=models.CharField(choices=[('>', '>'), ('<', '<'), ('>=', '>='), ('<=', '<='), ('=', '=')], max_length=2),
        ),
        migrations.AlterField(
            model_name='equivalencia',
            name='valor_letra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.ValoracionLetra'),
        ),
        migrations.AlterField(
            model_name='juicio',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Grado'),
        ),
        migrations.AlterField(
            model_name='juicio',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Grupo'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Grado'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Grupo'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Grado'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Grupo'),
        ),
    ]
