# Generated by Django 3.0.7 on 2020-06-30 18:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_auto_20200630_1214'),
        ('principal', '0003_auto_20200604_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='grado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='principal.Grado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='principal.Grupo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='jornda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Jornada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='principal.Profesor'),
            preserve_default=False,
        ),
    ]
