# Generated by Django 3.0.7 on 2020-06-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20200630_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fotografia',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='fotografia/', verbose_name='Dotografia'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='escudo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='escudo/', verbose_name='Escudo'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='fax',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='sitio_web',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
