# Generated by Django 3.0.7 on 2020-06-30 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('principal', '0007_auto_20200630_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='grupo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
