# Generated by Django 3.0.7 on 2020-06-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_auto_20200630_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='anio',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='colegio_ultimo_curso',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='direccion_colegio_ultimo_curso',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='direccion_padre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='motivo_retiro_ultimo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numero_documento_madre',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numero_documento_padre',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_colegio_ultimo_curso',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
