# Generated by Django 3.0.7 on 2020-06-30 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_auto_20200630_1214'),
        ('principal', '0010_auto_20200630_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='departamento_residencia_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamento_residencia_padre_set', to='configuracion.Departamento'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='empresa_acudiente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='municipio_residencia_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipio_residencia_padre_set', to='configuracion.Municipio'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='zona_residencia_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zona_residencia_padre_set', to='configuracion.Zona'),
        ),
    ]
