# Generated by Django 3.0.7 on 2020-07-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_auto_20200630_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_certificado_expulsion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_expulsion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='anio_matricula',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='fecha_matricula',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='fecha_creacion',
            field=models.DateField(blank=True),
        ),
    ]
